name: PiEngine CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build-test:

    strategy:
      matrix:
        compiler:
          - gcc
          - clang


    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache apt
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt
          key: ${{ runner.os }}-apt-v1
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache CMake
        uses: actions/cache@v4
        with:
          path: |
            build
          key: ${{ runner.os }}-${{ matrix.compiler }}-cmake-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.compiler }}-cmake-


      - name: Install Dependencies
        run: |
          sudo apt update

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt install -y \
              cmake \
              g++ \
              libgmp-dev \
              libtomlplusplus-dev \
              clang-format \
              clang-tidy
          else
            sudo apt install -y \
              cmake \
              clang \
              libgmp-dev \
              libtomlplusplus-dev \
              clang-format \
              clang-tidy
          fi


      - name: Configure
        run: |

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            export CXX=g++
          else
            export CXX=clang++
          fi


          cmake -S . -B build \
            -DENABLE_ASAN=ON \
            -DENABLE_UBSAN=ON


      - name: Build
        run: |
          cmake --build build


      - name: Format Check
        run: |
          clang-format --dry-run \
            $(find include src tests \
            \( -name '*.cpp' -o -name '*.hpp' \))


      - name: Static Analysis
        run: |
          clang-tidy \
            -p build \
            $(find src -name '*.cpp')


      - name: Test
        run: |
          ctest --test-dir build --output-on-failure
      
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.compiler }}
          path: |
            build/Testing


      - name: Upload Build Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.compiler }}
          path: |
            build